image: python:3.11

stages:
  - test

test:
  stage: test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  script:
    - pip install poetry
    - poetry install -v
    - poetry run tox
    - poetry run coverage run -m pytest
    - poetry run coverage report
  tags:
    - docker