image: python:3.11

stages:
  - test
  - deploy

test:
  stage: test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  script:
    - pip install poetry
    - poetry install -v
    - poetry run tox
    - poetry run coverage run -m pytest
    - poetry run coverage report
  tags:
    - docker

deploy-stable:
  stage: deploy
  script:
    - pip install poetry
    - poetry install -v
    - poetry build
    - echo "my-arithmetic-$USER deployment on stable servers"
    - ls dist/
  only:
    - tags
    - main
  tags:
    - docker

deploy-develop:
  stage: deploy
  script:
    - pip install poetry
    - poetry install -v
    - poetry build
    - echo "my-arithmetic-$USER deployment on develop servers"
    - ls dist/
  except:
    - main
  tags:
    - docker