test:
  stage: test
  image: python:3.11
  script:
    - pip install tox
    - tox
    - pip install coverage
    - coverage run -m pytest
  tags:
    - docker
badge:
  stage: badge
  image: python:3.11
  script:
    - pip install coverage-badge
    - coverage-badge -o media/badge.svg
  tags:
    - docker
  needs:
    - test
