test:
  stage: test
  image: python:3.11
  script:
    - pip install tox
    - tox
    - pip install pytest
    - pip install coverage
    - coverage run -m pytest
    - coverage report
  tags:
    - docker