name: My workflow

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - run: poetry install
      - run: poetry build
      - run: echo "my-arithmetic-joackim deployment on develop servers"
      - run: ls dist/
    if: github.ref != 'refs/heads/main'