name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: dschep/install-poetry-action@v1.3
        with:
          python-version: '3.11'
      - run: pip install tox
      - run: tox
      - run: poetry install
      - run: poetry run tox
      - run: poetry run coverage run -m pytest
      - run: poetry run coverage report
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: dschep/install-poetry-action@v1.3
      - run: poetry install
      - run: poetry build
      - run: echo "my-arithmetic-joackim deployment on stable servers"
      - run: ls dist/
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
