name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install tox
      - run: tox
      - run: pip install poetry
      - run: poetry install
      - run: poetry run tox
      - run: poetry run coverage run -m pytest
      - run: poetry run coverage report
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install
      - run: poetry build
      - run: echo "my-arithmetic-joackim deployment on stable servers"
      - run: ls dist/
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readthedocs/readthedocs-action@v2.4.0 # Utiliser une version spécifique de l'action
        with:
          token: ${{ secrets.RTD_TOKEN }}
          url: https://readthedocs.com/api/v2/
  
  coverage:
    runs-on: docker://python:3.11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install tox pytest coverage
      - run: tox
      - run: pip install poetry
      - run: poetry install
      - run: poetry run tox
      - run: poetry run coverage run -m pytest
      - run: poetry run coverage report
      - run: coverage run -m pytest
      - uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
          path-to-lcov: ./coverage/lcov.info # Spécifier le chemin du fichier lcov.info
