name: My workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: docker://python:3.11
    env:
      COVERAGE: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    steps:
      - uses: actions/checkout@v2
      - uses: dschep/install-poetry-action@v1.3
      - run: poetry install
      - run: poetry run tox
      - run: poetry run coverage run -m pytest
      - run: poetry run coverage report
  deploy:
    runs-on: docker://python:3.11
    steps:
      - uses: actions/checkout@v2
      - uses: dschep/install-poetry-action@v1.3
      - run: poetry install
      - run: poetry build
      - run: echo "my-arithmetic-joackim deployment on stable servers"
      - run: ls dist/
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
  deploy-dev:
    runs-on: docker://python:3.11
    steps:
      - uses: actions/checkout@v2
      - uses: dschep/install-poetry-action@v1.3
      - run: poetry install
      - run: poetry build
      - run: echo "my-arithmetic-joackim deployment on develop servers"
      - run: ls dist/
    if: github.ref != 'refs/heads/main'
